server:
  port: 8000
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_ADDRESS}
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: ${JAAS_CONFIG}
      security:
        protocol: SASL_SSL
    consumer:
      auto-offset-reset: earliest
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}/test1
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect