server:
  port: 8000
spring:
  kafka:
    bootstrap-servers: pkc-lzoyy.europe-west6.gcp.confluent.cloud:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='2O6ULB4ZBXB4WKCL' password='s4ijun9AJqKX7AVnbfTrAZuOC+G2RjLzSAjZ4mM0pD9t1SXgCcWCgIiq2lEj68mk';
      security:
        protocol: SASL_SSL
    consumer:
      auto-offset-reset: earliest
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5432/test1
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect